### ISSUE TITLE
Enable user references removal from Client.Web

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-lib#7]
## Description
As an Admin I want to be able to remove created references using Client.Web

## Acceptance criteria

- [ ] Admin is able to remove User references from Client.Web
- [ ] …

**Comment by techsmyth** [comment]
Issue moved to [cherrytwist/Client.Web #374](https://github.com/cherrytwist/Client.Web/issues/374) via [**ZenHub**](https://www.zenhub.com/)
